name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CatAPI.Net.sln

      - name: Build
        run: dotnet build CatAPI.Net.sln --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test CatAPI.Net.sln --no-build --configuration Release --logger trx

      - name: End-to-end integration test
        run: |
          cd src/CatApiClient.Sample
          dotnet run --configuration Release
